### ISSUE TITLE
File not existing

### ISSUE THREAD

**Issue by armandomm09** [wilmxre/react-native-mesh-gradient#1]
Heyyy, so I am having a problem where only by importing the library i gett this error:

Metro has encountered an error: While trying to resolve module
'react-native-
mesh-gradient from file '/Users/ Armando09/PROGRA2/javascript/reactNative/ baiaUI/app/index.jsx*, the package / Users/Armando09/PROGRA2/javascript/ reactNative/baiaUI/node_modules/react-native-mesh-gradient/package.json* was successfully found. However, this package itself specifies a 'main module field that could not be resolved (*/Users/ Armando09/PROGRA2/javascript/reactNative/ baiaUI/node_modules/react-native-mesh-gradient/lib/commonjs/index.js'. Indeed, none of these files exist:

* /Users/Armando09/PROGRA2/javascript/ reactNative/baiaUI/node_modules/react-native-mesh-gradient/lib/commonjs/ index.js(.ios.ts|.native.ts|.ts|.ios.tsx| .native.tsx|.tsx|.ios.mjs|.native.mjs|.mj s/.ios.js|.native.js|.js/.ios.jsx|.native
•jsx|.jsx.ios.json.native.json|.json.i os.cjs|.native.cjs|.cjs|.ios.scss|.native .scss|.scss|.ios.sass|.native.sass|.sass| .ios.css|.native.css|.css)
* /Users/Armando09/PROGRA2/javascript/ reactNative/baiaUI/node_modules/react-native-mesh-gradient/lib/commonjs/ index.js/ index(.ios.ts|.native.ts|.ts/.ios.tsx|.na tive.tsx|.tsx|.ios.mjs|.native.mjs|.mjs|. ios.js|.native.js|.js|.ios.jsx|.native.js x|.jsx|.ios.json|.native.json|.json|.ios. cjs|.native.cjs|.cjs|.ios.scss|.native.sc ss| .scss|.ios.sass|.native.sass|.sass|.10 s.css|.native.css|.css): /Users/ Armando09/PROGRA2/javascript/reactNative/ baiaUI/node_modules/metro/src/node-haste/ DependencyGraph.js (243:17)
241
}
242
if (error instanceof
InvalidPackageError) {
> 243 |
throw new
PackageResolutionError({
244
packageError: error,
245
originModulePath:from，
246 |
targetModuleName: to,

I did install the library and i got the error.

Things to coonsider:

 * I am using expo to run the app
 *  When viewing the installed module on /node_modules, the folder of 'react-native-mesh-gradient' only contains a package.json file
 * I tried installing the liibrary manually by downloading the zip from github and putting it with the correct name, in node_modules, and I got the same error
 

Hope anyone could help me, thank yoouu

**Comment by wilmxre** [comment]
hello. i corrected the package name on the github repo readme, but unfortunately i forgot to sync it with npm. 
please install the `@wilmxre/react-native-mesh-gradient` library instead of `react-native-mesh-gradient` and let me know if it works or not

**Comment by armandomm09** [comment]
Heyy, noo unfortunately doesn't works yet, do you know what else could it be?

**Comment by wilmxre** [comment]
also i updated the docs with information in regards to expo usage, please take a look at it at https://github.com/wilmxre/react-native-mesh-gradient?tab=readme-ov-file#expo-support

you will need to create a custom expo dev build, because expo-go doesn't support custom native modules. it is only a sandbox/playground environment, where you can play with the UI and with the native modules that are already built in the expo go app. these are expo specific packages, that are supported out-of-the-box.

when you create a custom dev build, you basically create your own "expo go" app, that includes custom native code.

**Comment by armandomm09** [comment]
And for creating playgrounf environment, you need to have an Apple Developer Program account right?

**Comment by wilmxre** [comment]
if you want to install the app on a real device, then yes, you will need an Apple Developer membership, but you can install it on a simulator without needing one. 
take a look at: https://docs.expo.dev/develop/development-builds/create-a-build/#create-a-build-for-emulatorsimulator

**Comment by wilmxre** [comment]
but for this you will need Xcode, which means you need to have a macbook

**Comment by armandomm09** [comment]
Cool cool thanks so much

**Comment by haikov** [comment]
@wilmxre hey! I encountered the same issue with the library, it looks like the build output is not included in the npm package. the main field of the package references `"module": "./lib/module/index.js",`, but `lib` folder is missing from the package itself https://www.npmjs.com/package/@wilmxre/react-native-mesh-gradient?activeTab=code. Might it be that the build command hasn't been ran prior to publishing the package?
